<a href="https://colab.research.google.com/github/AshishPal20/Machine-Learning-/blob/main/understanding_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Salary_Data.csv')

# **Questions regarding Dataset**

**1. How big is the data?**

In [ ]:
df.shape

(30, 2)

**2. how does the data look like ?**

In [ ]:
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [ ]:
df.sample(5)

    YearsExperience  Salary
5               2.9   56642
25              9.0  105582
13              4.1   57081
23              8.2  113812
21              7.1   98273

**3. What is the data type of cols?**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes

**4. Are there any missing values?**

In [ ]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

**5. How does data look mathematically ?**

In [ ]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

**6. Are there duplicate values?**

In [ ]:
df.duplicated().sum()

np.int64(0)

**7. How is the correlation between cols?**

In [ ]:
df.corr()['Salary']

YearsExperience    0.978242
Salary             1.000000
Name: Salary, dtype: float64